SLC/SLC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("login.urls")),
    path('listas/', include("listas.urls")),
]

SLC/listas/urls.py
from django.urls import path
from . import views

app_name = "listas"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:lista_id>", views.lista, name="lista"),
    path("<int:lista_id>/livro", views.livro, name="livro"),
    path("mercado", views.add_produto, name="mercado"),
    path("add_lista", views.add_lista, name="add_lista")
]

SLC/login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('', views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("cadastro", views.cadastro, name="cadastro")
]

SLC/listas/models.py
from django.db import models
from django import forms
from django.forms import ModelForm

# Create your models here.

class Lista(models.Model):
    nome_lista = models.CharField(max_length=64)
    
    def __str__(self):
        return f"{self.nome_lista}"

class Produto(models.Model):
    produto = models.CharField(max_length=64)
    preco = models.FloatField()
    nome = models.ManyToManyField(Lista, blank=True, related_name="nome")

    def __str__(self):
        return f"{self.produto} - R$  {self.preco}"


class NovaLista(ModelForm):
    class Meta:
        model = Lista
        fields = ['nome_lista']

class NovoProduto(ModelForm):
    class Meta:
        model = Produto
        fields = ['produto', 'preco']

SLC/login/models.py
from django.db import models

# Create your models here.

SLC/listas/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from .models import *
from django import forms
from django.db import transaction

# Create your views here.

def index(request):
    return render(request, "listas/index.html", {
        "listas": Lista.objects.all()
    })

def lista(request, lista_id):
    lista = Lista.objects.get(id=lista_id)
    produto = lista.nome.all()
    sem_lista = Produto.objects.exclude(id=lista_id).all()
    return render(request, "listas/lista.html", {
        "lista": lista,
        "produto": produto,
        "sem_lista": sem_lista
    })

def livro(request, lista_id):
    if request.method == "POST":
        lista = Lista.objects.get(pk=lista_id)
        produto_id = int(request.POST["produto"])
        produto = Produto.objects.get(pk=produto_id)
        produto.nome.add(lista)
        return HttpResponseRedirect(reverse("listas:lista", args=(lista.id,)))

def add_lista(request):
    if request.user.is_authenticated:
        formLista = NovaLista(request.POST or None)
        if formLista.is_valid():
            formLista.save()
        return render(request, 'listas/novalista.html', {
            'formLista': formLista
            })

def add_produto(request):
    if request.user.is_authenticated:
        formProduto = NovoProduto(request.POST or None)
        if formProduto.is_valid():
            formProduto.save()
        return render(request, 'listas/mercado.html', {
            'formProduto' : formProduto
            })

SLC/login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login


# Create your views here.

def index(request):
    return render(request, "login/index.html")

def login_view(request):
    if request.method == "GET":
        return render(request, "login/login.html")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user:
            auth_login(request, user)
            return HttpResponseRedirect(reverse("listas:index"))
        else:
            return render(request, "login/login.html", {
                "message": "Dados Incorretos"
            })

def cadastro(request):
    if request.method == "GET":
        return render (request, 'login/cadastro.html')
    else:
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = User.objects.filter(username=username).first()
        if user:
            return render(request, "login/cadastro.html", {
                "message": "Usuário existente"
            })

        user = User.objects.create_user(username=username, password=senha)
        user.save()

        return HttpResponseRedirect("login:index")

def logout_view(request):
    logout(request)
    return render(request, "login/index.html", {
                "message": ""
            })

SLC/listas/templates/listas/index.html
{% extends "listas/layout.html" %}

{% block body %}
    <h1>Listas:</h1>
    <ul>
        {% for listas in listas %}
            <li><a id="itens" href="{% url 'listas:lista' listas.id %}">{{ listas.nome_lista }}</a></li>
        {% endfor %}
    </ul>
    <h3><a id="add" href="{% url 'listas:add_lista' %}">Adicionar Lista</a></h3>
    <h3><a id="add" href="{% url 'listas:mercado' %}">Mercado</a></h3>

    <a id="sair" href="{% url 'login:logout' %}">Log Out</a>
{% endblock %}

SLC/listas/templates/listas/layout.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title>Listas de Compras</title>
        <style>
            body{
                background-color: rgb(163, 211, 156);
                margin-left: 50px;
            }
            h1 {
                font-family: 'Trebuchet MS';
                color: aliceblue;
                margin-top: 100px;
                font-size: 75px;
            }
            ul{
                list-style-type: decimal;
                color: aliceblue;
                font-family: 'Trebuchet MS';
                font-size: 25px;
                margin-left: 50px;
            }
            #itens{
                text-decoration: none;
                color: rgb(0, 55, 104);
                font-size: 20px;
                font-family: 'Trebuchet MS';
                letter-spacing: 2px;
                transition: .5s;
            }
            #itens:hover{
                color: aliceblue;
            }
            #add{
                border: black 2px solid;
                padding: 4px;
                text-decoration: none;
                color: aliceblue;
                font-family: 'Trebuchet MS';
                letter-spacing: 1px;
                display: inline-block;
                width: 200px;
                height: 20px;
                text-align: center;
                border-radius: 4px;
                font-size: 20px;
                transition: .5s;
                background-color: darkolivegreen;
            }
            #add:hover{
                cursor: pointer;
                background-color: aliceblue;
                color: black;
            }
            #sair{
                border: black 2px solid;
                font-family: 'Trebuchet MS';
                border-radius: 4px;
                color: aliceblue;
                padding: 4px;
                text-decoration: none;
                text-align: center;
                display: inline-block;
                width: 100px;
                height: 20px;
                transition: .5s;
                background-color: crimson;
            }
            #sair:hover{
                cursor: pointer;
                background-color: aliceblue;
                color: black;
            }
            h2{
                font-family: 'Trebuchet MS';
                font-size: 40px;
            }
            #produtos{
                font-family: 'Trebuchet MS';
                font-size: 20px;
                letter-spacing: 1px;
            }
            #back{
                border: black 2px solid;
                font-family: 'Trebuchet MS';
                border-radius: 4px;
                color: aliceblue;
                padding: 4px;
                text-decoration: none;
                text-align: center;
                display: inline-block;
                width: 150px;
                height: 20px;
                transition: .5s;
                background-color:darkolivegreen;
            }
            #back:hover{
                cursor: pointer;
                background-color: aliceblue;
                color: black;
            }
            form{
                font-family: 'Trebuchet MS';
                color: aliceblue;
                font-size: 20px;
                letter-spacing: 1px;
            }
            input{
                border: solid 2px black;
                border-radius: 4px;
                height: 40px;
                width: 200px;
                font-size: 20px;
                margin-top: 10px;
            }
            #confirma{
                background-color: aliceblue;
                transition: .5s;
            }
            #confirma:hover{
                cursor: pointer;
                background-color: rgb(60, 205, 253);
            }
            select{
                border: solid 2px black;
                border-radius: 4px;
                height: 40px;
                width: 200px;
                font-size: 20px;
                margin-top: 10px;
                background-color: aliceblue;
            }
            select:hover{
                cursor: pointer;
            }
        </style>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

SLC/listas/templates/listas/lista.html
{% extends "listas/layout.html" %}

{% block body %}
    <h1>Lista: {{ lista.nome_lista }}</h1>
    <a id="back" href="{% url 'listas:index' %}">Todas as Listas</a>

    <h2>Produtos:</h2>
    <ul id="produtos">
        {% for produto in produto %}
            <li><b>{{ produto }}</b></li>
        {% empty %}
            <li>Sem Produtos</li>
        {% endfor %}
    </ul>

    <form action="{% url 'listas:livro' lista.id %}" method="post">
        {% csrf_token %}
        <select name="produto" id="">
            {% for produto in sem_lista %}
                <option value="{{ produto.id }}">{{ produto }}</option>
            {% endfor %}
        </select>
        <input id="confirma" type="submit" value="Adicionar">
    </form>

{% endblock %}

SLC/listas/templates/listas/mercado.html
{% extends "listas/layout.html" %}

{% block body %}
    <h1>Mercado:</h1>
    <form method="post" aria-required="false">
        {% csrf_token %}
        {{formProduto.as_p}}
        <input id="confirma" type="submit" value="Adicionar">
    </form>
    <br>
    <a id="back" href="{% url 'listas:index' %}">Todas as Listas</a>
{% endblock %}

SLC/listas/templates/listas/novalista.html
{% extends "listas/layout.html" %}

{% block body %}
<h1>Adicionar Lista:</h1>
    <form method="post" aria-required="false">
        {% csrf_token %}
        {{formLista.as_p}}
        <input id="confirma" type="submit" value="Adicionar">
    </form>
    <br>
    <a id="back" href="{% url 'listas:index' %}">Todas as Listas</a>
{% endblock %}

SLC/login/templates/login/cadastro.html
{% extends "login/layout.html" %}

{% block body %}
<h1>Cadastro:</h1>
{% if message %}
    <div>{{ message }}</div>
{% endif %}
<br>
    <form action="{%url 'login:cadastro' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Nome de Usuário" name="username">
        <br>
        <input type="password" placeholder="Senha" name="senha">
        <br>
        <input id="confirma" type="submit" value="Cadastrar">
    </form>
    <br>
    <a id="voltar" href="{%url 'login:index' %}">Voltar</a>
{% endblock %}

SLC/login/templates/login/index.html
{% extends "login/layout.html" %}

{% block body %}
    <h1>Cadastro e Login</h1>
    <h3><a id="inicio" href="{% url 'login:cadastro' %}"> Cadastre-se!</a></h3>
    <h3><a id="inicio" href="{% url 'login:login' %}"> Login!</a></h3>
{% endblock %}

SLC/login/templates/login/layout.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title>Login</title>
        <style>
            body{
                background-color: rgb(163, 211, 156);
                text-align: center;
            }
            h1 {
                font-family: 'Trebuchet MS';
                color: aliceblue;
                margin-top: 100px;
                font-size: 75px;
            }
            #inicio {
                border: black 2px solid;
                padding: 4px;
                text-decoration: none;
                color: aliceblue;
                font-family: 'Trebuchet MS';
                letter-spacing: 1px;
                display: inline-block;
                width: 400px;
                height: 50px;
                text-align: center;
                border-radius: 4px;
                font-size: 40px;
                transition: .5s;
                background-color: darkolivegreen;
            }
            #inicio:hover{
                cursor: pointer;
                background-color: aliceblue;
                color: black;
            }
            input{
                border: solid 2px black;
                border-radius: 4px;
                height: 50px;
                width: 200px;
                font-size: 20px;
                text-align: center;
                margin-top: 10px;
            }
            #voltar{
                border: black 2px solid;
                padding: 4px;
                text-decoration: none;
                color: aliceblue;
                font-family: 'Trebuchet MS';
                letter-spacing: 1px;
                display: inline-block;
                width: 100px;
                height: 20px;
                text-align: center;
                border-radius: 4px;
                font-size: 20px;
                transition: .5s;
                background-color: darkolivegreen;
            }
            #voltar:hover{
                cursor: pointer;
                background-color: aliceblue;
                color: black;
            }
            #confirma{
                background-color: aliceblue;
                transition: .5s;
            }
            #confirma:hover{
                cursor: pointer;
                background-color: rgb(60, 205, 253);
            }
        </style>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

SLC/login/templates/login/login.html
{% extends "login/layout.html" %}

{% block body %}
<h1>Informe os Dados:</h1>
{% if message %}
    <div>{{ message }}</div>
{% endif %}
<br>
    <form action="{% url 'login:login' %}" method="post">
        {% csrf_token %}
        <input type="text", name="username", placeholder="Nome de Usuário">
        <br>
        <input type="password", name="password", placeholder="Senha">
        <br>
        <input id="confirma" type="submit", value="Login">
    </form>
    <br>
    <a id="voltar" href="{%url 'login:index' %}">Voltar</a>
{% endblock %}